/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sayit;

import javax.swing.SwingUtilities;

/**
 * Start running the app
 */
public class App {
  public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
      new Mediator();
    });
  }
}