/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sayit.UI;

import java.io.IOException;
import javax.swing.SwingUtilities;
import sayit.Server.MockServer;
import sayit.Server.Server;

/**
 * Start running the app
 */
public class App {
  public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
      // Start the web server
      try {
        /* Uncomment whichever server to use and comment out other */
        MockServer.startServer();
        //Server.startServer(filePath);
      } catch (Exception e) {
        System.out.println("App.java: " + e);
        e.printStackTrace();
      }

      // Create the UI
      new Login();
    });
  }
}