/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sayit.UI;

import java.io.IOException;
import javax.swing.SwingUtilities;
import sayit.Server.Server;
import sayit.Server.BusinessLogic.MockMediator;

/**
 * Start running the app
 */
public class App {
  public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
      // Create the UI
      new AppFrame();

      // Start the web server
      try {
        Server.startServer();
      } catch (IOException e) {
        System.out.println("App.java: " + e);
        e.printStackTrace();
      }
    });
  }
}