/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sayit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;

class PromptHistoryTest {
    private PromptHistory myHistory;
    private PromptHistory newLineHistory;
    private final String FILE_TEST3_PATH = "src/test/java/sayit/Test-files/test-3.txt";
    private final String FILE_EMPTY_PATH = "src/test/java/sayit/Test-files/empty.txt";

    @BeforeEach
    void setup(){
        myHistory = new PromptHistory(FILE_TEST3_PATH); //Use my six line test file
        newLineHistory = new PromptHistory(FILE_EMPTY_PATH);
    }

    @Test
    void testNonEmpty(){
        //Pair 1:
        assertEquals(myHistory.getQuery(0), "What's the best ice cream flavor");
        assertEquals(myHistory.getAnswer(0), "Obviously it's cookie's and cream");
        
        //Pair 2
        assertEquals(myHistory.getQuery(1), "Cats or dogs");
        assertEquals(myHistory.getAnswer(1), "Dogs are more easily manipulatable so I'd choose them");
        
        //Pair 3
        assertEquals(myHistory.getQuery(2), "Would you go out on a date with me");
        assertEquals(myHistory.getAnswer(2),
             "Unfortunaley I can not, but I would reccommend going outside and touching some grass");

        // Size comparison
        assertEquals(myHistory.getSize(), 3);
    }

    @Test
    void testKindaEmpty(){
        //Pair 1:
        assertEquals(newLineHistory.getQuery(0), ""); //I think thats how the interaction would work if not then ""
        assertEquals(newLineHistory.getAnswer(0), "");
        
        // Size Comparison
        assertEquals(newLineHistory.getSize(), 1);
    }

    @Test
    void testClearAll() {
        // make sure ArrayList is not empty
        assertNotEquals(0, myHistory.getSize());
        
        // make sure that the clearAll clears the ArrayList
        myHistory.clearPrompts();
        assertEquals(0, myHistory.getSize());

        // make sure that the clearAll keeps ArrayList size 0
        myHistory.clearPrompts();
        assertEquals(0, myHistory.getSize());
    }
}
